// app/utils/data.ts
import { EventItem, MerchItem, SponsorItem } from "@/types";

export const EVENTS: EventItem[] = [
  {
    id: "ideathon",
    icon: "💡",
    name: "IdeaThon",
    tagline: "Design for Sustainable Impact",
    description:
      "Teams identify a real area-based challenge or build a new value-driven concept with sustainability at the center.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#ff88aa",
    day: 1,
    teamSize: "2-4 participants",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Innovation", "Sustainability", "Presentation"],
    rules: [
      "Use of AI tools/design software is permitted, but originality must be maintained.",
      "Plagiarism or copying of existing projects will lead to disqualification.",
      "Time slots for presentation will be strictly followed.",
      "The decision of the judges will be final and binding.",
    ],
    guidelines: [
      "Team Formation: Each team can consist of 2-4 participants. Participants can be from the same or different departments. Cross-disciplinary collaboration is encouraged.",
      "Problem Statement: A large area layout will be provided by the organizers. Teams must select a specific portion of the area and either solve an existing problem or create something new.",
      "Focus on Sustainability: Solutions must align with sustainable development goals and prioritize eco-friendly, resource-efficient, long-term viable methods.",
      "Deliverables: Submit a sketch/diagram/layout and a 5-7 minute presentation before the deadline.",
      "Evaluation Criteria: Innovation & Creativity, Relevance, Sustainability, Feasibility, Presentation, Cross Questioning.",
      "General Instructions: Bring stationery and laptop (if required); follow timeline and coordinate with organizers for queries.",
    ],
  },
  {
    id: "verilog-coding",
    icon: "🧠",
    name: "VERILOG CODING",
    tagline: "Digital Logic by Code",
    description:
      "Participants design and implement digital circuits using Verilog HDL under time constraints.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#00f5ff",
    day: 1,
    teamSize: "individual only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Verilog", "EDA Playground", "Individual"],
    rules: [
      "Participants must bring their own laptops with access to EDA Playground.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; participation is individual only.",
      "Format: Design and implement digital circuits using Verilog HDL.",
      "Duration: As per event schedule.",
      "Evaluation: Based on correctness, efficiency, and optimization.",
    ],
  },
  {
    id: "line-follower-robot",
    icon: "🤖",
    name: "LINE FOLLOWER ROBOT",
    tagline: "Speed with Precision",
    description:
      "Autonomous robots must accurately follow a predefined black-line track on a white surface.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#ffd700",
    day: 1,
    teamSize: "groups of max 3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Autonomous", "IR Sensors", "Robotics"],
    rules: [
      "Only IR sensors or light sensors may be used for line detection.",
      "Robots must adhere to max dimensions (25cm x 25cm) and weight (2kg).",
      "External wireless/manual control is prohibited.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; participation in groups of max 3 members.",
      "Format: Robots must autonomously follow a track marked with black lines on white surface.",
      "Duration: As per event schedule.",
      "Evaluation: Accuracy, speed, and penalties for leaving track/manual intervention.",
    ],
  },
  {
    id: "water-filtration-race",
    icon: "💧",
    name: "Water Filtration Race",
    tagline: "Clarity Under Pressure",
    description:
      "Teams build a filter on the spot using organizer kits and compete on clarity, speed, and design.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "15k for prize pool",
    fee: "TBA",
    color: "#4ade80",
    day: 1,
    teamSize: "2-3 members per team",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Filtration", "Lab Test", "Design Build"],
    rules: [
      "No external material is allowed; only organizer-provided kit can be used.",
      "Inter college team members are not allowed.",
      "Inter specialization are allowed.",
      "Time limit: Max 90 minutes (30 min design + 60 min filtering).",
      "Filter must be stable and fill filtered water at given specific container height.",
      "Disqualification for unapproved materials, spillage, or failure within time.",
    ],
    guidelines: [
      "Eligibility: For all B.E., B.Tech, and other college students.",
      "All teams receive equal testing water quantity; testing done in laboratory with digital turbidity meter.",
      "Scoring (100 points): Clarity 50, Filtration speed 30, Design and innovation 20.",
    ],
  },
  {
    id: "minimalist-circuit-challenge",
    icon: "🧩",
    name: "Minimalist Circuit Challenge",
    tagline: "Do More with Less",
    description:
      "Teams design and build optimized circuits using minimum components with strong reliability and clarity.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "Winner Team: ₹7,000 - Runner-Up Team: 5,000",
    fee: "TBA",
    color: "#60a5fa",
    day: 1,
    teamSize: "A team must consist of 2-3 members",
    resultAnnouncement: null,
    dayTimeVenue: "To be Announced",
    tags: ["Circuit Build", "Optimization", "State Only"],
    rules: [
      "Team size: 2-3 members.",
      "Time limit: 2.5 hours for circuit building.",
      "Only provided components are allowed.",
      "All circuits must be built on-site; pre-built modules are not allowed.",
      "Safety guidelines must be followed.",
      "Judges' decision is final.",
      "Teams from outside the state are not eligible.",
      "Inter-college and inter-branch teams are permitted within the state.",
      "Any violation leads to disqualification.",
    ],
    guidelines: [
      "Open only to students currently enrolled in state engineering, diploma, or science programs.",
      "Inter-college and inter-specialization teams are allowed within the state.",
      "Round 1: Problem statement selection.",
      "Round 2: Design and implementation (2.5 hours).",
      "Round 3: Presentation and evaluation.",
      "Judging: Innovation 25%, Implementation 25%, Efficiency 25%, Teamwork and explanation 25%.",
    ],
  },
  {
    id: "rocket-aviation-task",
    icon: "🚀",
    name: "ROCKET AVIATION TASK",
    tagline: "Model, Validate, Present",
    description:
      "Participants bring pre-made models and are evaluated for feasibility and solution clarity.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#f97316",
    day: 1,
    teamSize:
      "Group of max 3 member and individual participation is also allowed",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Aviation", "Model Based", "Engineering"],
    rules: [
      "Only provided tools/software may be used.",
      "External reference materials are not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students.",
      "Format: Participants bring their pre-made model at competition time.",
      "Duration: 60 minutes.",
      "Evaluation: Accuracy, feasibility, and clarity of solution.",
    ],
  },
  {
    id: "circuit-debugging",
    icon: "🔧",
    name: "CIRCUIT DEBUGGING",
    tagline: "Find Faults, Restore Function",
    description:
      "A multi-round debugging challenge with MCQs, circuit design, and real fault-finding under strict timing.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#06b6d4",
    day: 1,
    teamSize: "Teams of 1-3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Debugging", "E&E", "Round Based"],
    rules: [
      "Teams must consist of 1-3 members from the same institute.",
      "Only Electrical and Electronics specialization students are eligible.",
      "Inter-NIT collaboration is strictly not allowed.",
      "Unauthorized reference material, internet, or devices are prohibited.",
      "Judges and coordinators decisions are final and binding.",
      "Participants must strictly follow round time limits.",
      "Misconduct or rule violations lead to immediate disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to NIT Arunachal Pradesh Electrical and Electronics branch specializations only.",
      "Team Formation: Teams of 1-3 members.",
      "Round 1: 20 debugging questions, 25 minutes.",
      "Round 2: Top 10 design optimized circuits from 2 problem statements, 20 minutes.",
      "Round 3: Top 5 debug and test one faulty circuit, 20 minutes.",
      "Evaluation: Error identification, creativity, efficiency, practical debugging, time management, and clarity.",
    ],
  },
  {
    id: "bridge-making",
    icon: "🌉",
    name: "Bridge making",
    tagline: "Strength Meets Aesthetics",
    description:
      "Teams build bridges using only provided sticks and glue, then face progressive center-load failure testing.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#a78bfa",
    day: 2,
    teamSize: "2-3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Structures", "Load Test", "Civil Build"],
    rules: [
      "Inter college team members are not allowed.",
      "Inter specialization are allowed.",
      "Any extra glue, tape, string, wire, nails, pins, or materials lead to disqualification.",
      "No external cables, wires, or reinforcements are allowed.",
      "Teams must bring completed bridge for inspection/testing on competition day.",
      "Non-compliant bridges may be rejected before testing.",
      "Only organizers/judges handle loading process.",
      "Disqualification for violating material and dimension/submission rules.",
    ],
    guidelines: [
      "Eligibility: B.E./B.Tech and other college students.",
      "Team size: 2-3 members.",
      "Materials: Organizer-provided ice-cream sticks and glue only.",
      "Design: Any bridge type (beam, truss, arch, etc.) using provided materials.",
      "Dimensions: Length min 55 cm, clear span 50 cm, deck width min 15 cm, no height restriction.",
      "Construction: Allowed before competition day but only with provided materials.",
      "Load Testing: Gradual center loading until failure.",
      "Evaluation: Strength 70%, aesthetics and neatness 30%.",
    ],
  },
  {
    id: "pcb-design",
    icon: "🟩",
    name: "PCB DESIGN",
    tagline: "From Schematic to 3D Board",
    description:
      "Teams design and simulate PCBs from given specs up to final 3D PCB output.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#22c55e",
    day: 2,
    teamSize: "teams of 1-2 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["PCB", "Simulation", "Layout"],
    rules: [
      "Only professional design software is allowed.",
      "Pre-prepared designs are strictly prohibited.",
      "Internet access during the round is not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; teams of 1-2 members.",
      "Format: Design and simulate PCB from given specification to final 3D design.",
      "Duration: As per event schedule.",
      "Evaluation: Correctness, layout optimization, industry practices, creativity, minimal track length.",
    ],
  },
  {
    id: "maze-follower-robot",
    icon: "🧭",
    name: "MAZE FOLLOWER ROBOT",
    tagline: "Autonomous Pathfinding",
    description:
      "Robots must autonomously navigate a maze from start to finish with high speed and accuracy.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#eab308",
    day: 2,
    teamSize: "groups of max 3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Autonomous", "Maze", "Robotics"],
    rules: [
      "Robots must operate autonomously with no external/manual control.",
      "Modifications during the round are not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; groups of max 3 members.",
      "Format: Robots navigate through maze autonomously from start to finish.",
      "Duration: As per event schedule.",
      "Evaluation: Speed and accuracy.",
    ],
  },
  {
    id: "mortal-kombat-showdown",
    icon: "🎮",
    name: "Mortal Kombat Showdown",
    tagline: "Controller Skill Arena",
    description:
      "Tournament format adapts to participation size with best-of match rounds and fair-play enforcement.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "₹15,000",
    fee: "TBA",
    color: "#ef4444",
    day: 2,
    teamSize: "Players register individually",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Esports", "Knockout", "1v1"],
    rules: [
      "Format is knockout or league-cum-knockout based on participant count.",
      "Matches on standard setups with provided controllers; personal controllers may be allowed.",
      "Each match best of 3 rounds; finals best of 5 rounds.",
    ],
    guidelines: [
      "Registration and briefing include rules, format, judging criteria, fair-play, and disqualification conditions.",
      "Participation through the official Google Form.",
    ],
  },
  {
    id: "component-identification",
    icon: "🔌",
    name: "Component Identification",
    tagline: "Know It, Use It, Build It",
    description:
      "A four-round identification and application challenge progressing from written tests to buzzer finals.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "1st: ₹6,000, 2nd: ₹4,000, 3rd: ₹2,000",
    fee: "TBA",
    color: "#14b8a6",
    day: 2,
    teamSize: "Individual participation only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Electronics", "Rounds", "Identification"],
    rules: [
      "Participants must report 15 minutes before event starts.",
      "Only qualified participants proceed to next round.",
      "External materials, gadgets, or mobile phones are prohibited.",
      "Judges' decisions are final and binding.",
      "Any misconduct leads to disqualification.",
    ],
    guidelines: [
      "Competition has 4 rounds; both inter-college and inter-specialization participation are allowed.",
      "Round 1: 30 questions (25 MCQ + 5 theoretical), 35 minutes; 15 qualify.",
      "Round 2: Identify components and state usage/applications, 20 minutes; 10 qualify.",
      "Round 3: Circuit completion and missing element identification, 30 minutes; 5 qualify.",
      "Round 4: Final buzzer round (WHO AM I?) for 30 minutes.",
    ],
  },
  {
    id: "assembly-disassembly",
    icon: "🛠️",
    name: "ASSEMBLY & DISASSEMBLY",
    tagline: "Accuracy Under Time",
    description:
      "Participants disassemble and reassemble mechanical systems correctly, focusing on speed and part identification.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#64748b",
    day: 2,
    teamSize: "individual only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Mechanical", "Hands On", "Individual"],
    rules: [
      "Safety gear (gloves, goggles) must be worn at all times.",
      "Mishandling or damaging components will result in disqualification.",
      "Only provided tools may be used.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; individual participation only.",
      "Format: Disassemble and reassemble the given mechanical component/system within the time limit.",
      "Duration: 60 minutes.",
      "Evaluation: Accuracy, speed, and proper identification of parts.",
    ],
  },
  {
    id: "rc-rush",
    icon: "🏎️",
    name: "RC Rush: Radio Controlled Car Racing Challenge",
    tagline: "Build Fast, Race Smart",
    description:
      "Teams design and build custom RC cars, then compete through heats, semis, and finals on obstacle tracks.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "₹25,000 (1st: 15k, 2nd: 8k, 3rd: 2k)",
    fee: "TBA",
    color: "#f43f5e",
    day: 3,
    teamSize: "Team comprising 2-4 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["RC", "Racing", "Vehicle Design"],
    rules: [
      "Participants must design and build their own RC cars; ready-made cars are not permitted.",
      "Maximum dimensions: 40 cm length x 25 cm width.",
      "Power source must be battery-operated only; no fuel engines.",
      "Cars must be controlled wirelessly; 2.4 GHz modules recommended.",
      "Cars are inspected for size, power, and safety compliance.",
    ],
    guidelines: [
      "Briefing covers rules, size restrictions, power sources, and judging criteria.",
      "Design should prioritize speed, maneuverability, and stability.",
      "Creativity, lightweight design, and material efficiency add value.",
      "Cars must be submitted for inspection before race.",
      "Race rounds include heats, semi-finals, and finals on tracks with turns and obstacles.",
      "Scoring: Speed, control, and endurance.",
    ],
  },
  {
    id: "circuit-problem-solving",
    icon: "📐",
    name: "CIRCUIT PROBLEM SOLVING",
    tagline: "Paper Logic Sprint",
    description:
      "Teams solve digital circuit problems on paper using standard logic cells and clear block diagrams.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#3b82f6",
    day: 3,
    teamSize: "teams of 1-2 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Logic Design", "Paper Round", "Digital Circuits"],
    rules: [
      "Only standard paper and provided stationery may be used.",
      "External reference materials are not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; teams of 1-2 members.",
      "Format: Create block diagram solution using standard cells (AND, OR, XOR, Adder, Counter, etc.).",
      "Duration: As per event schedule.",
      "Evaluation: Accuracy, speed, and clarity of explanation.",
    ],
  },
  {
    id: "robowar-13-5kg",
    icon: "⚔️",
    name: "Robowar - 13.5 kg Category",
    tagline: "Arena Combat Engineering",
    description:
      "Combat robots battle under strict safety constraints with scoring focused on damage, aggression, control, and strategy.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "₹30,000",
    fee: "TBA",
    color: "#8b5cf6",
    day: 3,
    teamSize: "Max 6 members per team",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Combat Robotics", "Safety Check", "Arena"],
    rules: [
      "Match duration: 3 minutes, with 1-minute extension in tie.",
      "Winning by knockout, out-of-arena, or judges decision.",
      "Judging: Damage 40%, Aggression 30%, Control 20%, Strategy 10%.",
      "One technical timeout (2 min max) allowed between matches.",
      "Only 2 members may stay near arena during match.",
      "All robots must pass safety inspection.",
      "Intentional arena damage is prohibited.",
      "Leaving arena causes disqualification.",
      "Illegal weapons/safety violations/unsportsmanlike conduct lead to disqualification.",
    ],
    guidelines: [
      "Weight limit: Max 13.5 kg including batteries and weapons; tolerance +-500 g.",
      "Dimensions: Must fit through approx 3 ft x 3 ft gate.",
      "Mobility: Wheels, tracks, legs allowed; flying bots/drones not allowed.",
      "Electrical power: Max 48 V with insulated connections.",
      "Pneumatics: Max 8 bar (120 psi) with relief valves and regulators.",
      "Allowed weapons: Spinners, drums, bars, wedges, hammers, crushers, flippers.",
      "Prohibited weapons: Explosives, fire, corrosives, nets, glue, liquids, projectiles, jammers.",
    ],
  },
  {
    id: "bgmi",
    icon: "🎯",
    name: "BGMI",
    tagline: "Squad Tactics Championship",
    description:
      "Teams advance from qualifiers to finals over multiple maps using official point systems and strict fair-play rules.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "Prize Pool: ₹10,000 (1st: ₹5,000, 2nd: ₹3,000, 3rd: ₹2,000)",
    fee: "TBA",
    color: "#f59e0b",
    day: 3,
    teamSize: "6 members (4 main players + 2 substitutes optional)",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Esports", "Squad", "Battle Royale"],
    rules: [
      "No tablets or emulators; only mobile phones are allowed.",
      "Third-party apps, hacks, or cheats lead to immediate disqualification.",
      "Only registered players (main/substitute) may play; violations disqualify full team.",
      "Additional in-game rules will be shared before event starts.",
    ],
    guidelines: [
      "Qualifiers: Teams divided into lobbies; top performers advance.",
      "Qualified teams play Erangle, Miramar, Sanhok, and Vikendi.",
      "Finals determine winner by cumulative point system.",
      "Registration via official Google Form with all team member details.",
    ],
  },
  {
    id: "solidworks-design",
    icon: "📦",
    name: "SOLIDWORKS DESIGN",
    tagline: "Model with Precision",
    description:
      "Participants solve a given design problem in SolidWorks, emphasizing accuracy, efficiency, and innovation.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#10b981",
    day: 3,
    teamSize: "individual only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["CAD", "SolidWorks", "Individual"],
    rules: [
      "Bring own laptop with licensed/student SolidWorks installed.",
      "Pre-prepared models or external files are prohibited.",
      "Internet access during round is not allowed.",
      "Mobile phones are not permitted during competition.",
      "Judges' decisions are final.",
      "Any malpractice leads to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; individual participation only.",
      "Format: Given design problem modeled in SolidWorks.",
      "Duration: 120 minutes.",
      "Evaluation: Accuracy, design efficiency, time, innovation.",
    ],
  },
  {
    id: "hydraulic-arm-task",
    icon: "🦾",
    name: "HYDRAULIC ARM TASK",
    tagline: "Control Force with Finesse",
    description:
      "Participants assemble and operate hydraulic arm mechanisms to handle given loads accurately and efficiently.",
    date: "Day 3",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#ec4899",
    day: 3,
    teamSize:
      "Group of max 3 member and individual participation is also allowed",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Hydraulics", "Mechanical", "Control"],
    rules: [
      "Only provided components/software tools may be used.",
      "Pre-prepared designs or external help are not allowed.",
      "Proper handling of hydraulic components is mandatory; mishandling leads to disqualification.",
      "Safety precautions must be followed at all times.",
      "Mobile phones are not permitted during competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students.",
      "Format: Operate hydraulic arm based on given weights.",
      "Duration: 60 minutes.",
      "Evaluation: Assembly accuracy, smooth operation, efficiency, innovation.",
    ],
  },
];

export const ROADMAP = [
  {
    day: 1,
    date: "April 9",
    title: "Opening Day",
    subtitle: "Culture Awakens",
    color: "#ff88aa",
    schedule: [
      { time: "8:00 AM", event: "Registration & Inauguration" },
      { time: "9:00 AM", event: "Inaugural Function" },
      { time: "10:00 AM", event: "Solo Classical" },
      { time: "11:00 AM", event: "Solo Western" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Group Classical" },
      { time: "2:00 PM", event: "Group Western" },
      { time: "3:00 PM", event: "Dance Finals" },
      { time: "4:00 PM", event: "Prize Distribution" },
      { time: "5:00 PM", event: "Band Performance" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 1" },
    ],
  },
  {
    day: 2,
    date: "April 10",
    title: "Battle Day",
    subtitle: "Legends Clash",
    color: "#9b59f5",
    schedule: [
      { time: "8:00 AM", event: "Registration" },
      { time: "9:00 AM", event: "Drama Competition" },
      { time: "10:00 AM", event: "Skit Competition" },
      { time: "11:00 AM", event: "Mono Act" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Gaming Competition" },
      { time: "2:00 PM", event: "Technical Events" },
      { time: "3:00 PM", event: "Singing Competition" },
      { time: "4:00 PM", event: "Instrumental Performance" },
      { time: "5:00 PM", event: "Battle of Bands" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 2" },
    ],
  },
  {
    day: 3,
    date: "April 11",
    title: "Star Night",
    subtitle: "Champions Rise",
    color: "#ffd700",
    schedule: [
      { time: "8:00 AM", event: "Registration" },
      { time: "9:00 AM", event: "Art Competition" },
      { time: "10:00 AM", event: "Photography Competition" },
      { time: "11:00 AM", event: "Mehandi Competition" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Fashion Show" },
      { time: "2:00 PM", event: "Singing Finals" },
      { time: "3:00 PM", event: "Dance Finals" },
      { time: "4:00 PM", event: "Prize Distribution" },
      { time: "5:00 PM", event: "Band Performance" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 3" },
    ],
  },
];

export const MERCH: MerchItem[] = [
  {
    id: "black-tshirt",
    name: "Black Festival Tee",
    description:
      "Premium black cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/Black_Dragon.jpg__1_-removebg-preview.png",
    color: "#000000",
    tag: "Classic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ffffff",
    glowColor: "#ffd700",
  },
  {
    id: "white-tshirt",
    name: "White Festival Tee",
    description:
      "Premium white cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/White_Fish.jpg-removebg-preview.png",
    color: "#ffffff",
    tag: "Fresh",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ff0000",
  },
  {
    id: "sakura-tshirt",
    name: "Sakura Festival Tee",
    description:
      "Premium cotton tee with ATULYAM sakura design featuring Japanese cherry blossom elements and festival logo.",
    price: 350,
    icon: "/images/merch/Beige_Sakura.jpg-removebg-preview.png",
    color: "#be185d",
    tag: "Spring Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
  {
    id: "galaxy-tshirt",
    name: "Galaxy Festival Tee",
    description:
      "Premium cotton tee with ATULYAM galaxy design featuring stars and cosmic elements on the back.",
    price: 350,
    icon: "/Beige_Dragon.jpg-removebg-preview.png",
    color: "#4a5568",
    tag: "Limited Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
];

export const SPONSORS: SponsorItem[] = [
  {
    name: "NovaTech",
    tier: "title",
    emoji: "🌟",
    desc: "Driving innovation in technology and education across India.",
    logo: "🚀",
  },
  {
    name: "StarByte",
    tier: "platinum",
    emoji: "⬡",
    desc: "AI-first software studio powering next-gen digital products.",
    logo: "🤖",
  },
  {
    name: "Haru Media",
    tier: "platinum",
    emoji: "🌸",
    desc: "Pan-Asia media and content company celebrating youth culture.",
    logo: "📺",
  },
  {
    name: "CosmicFX",
    tier: "gold",
    emoji: "✦",
    desc: "Visual effects and post-production studio.",
    logo: "🎬",
  },
  {
    name: "NebulaWorks",
    tier: "gold",
    emoji: "◈",
    desc: "Deep-tech startup accelerator and venture studio.",
    logo: "🌌",
  },
  {
    name: "SakuraTech",
    tier: "gold",
    emoji: "✿",
    desc: "Consumer hardware and wearables brand.",
    logo: "⌚",
  },
  {
    name: "ZenithCorp",
    tier: "associate",
    emoji: "◆",
    desc: "B2B SaaS and enterprise solutions.",
    logo: "💼",
  },
  {
    name: "PulseStudio",
    tier: "associate",
    emoji: "◉",
    desc: "Creative agency for music and events.",
    logo: "🎨",
  },
  {
    name: "VoidLabs",
    tier: "associate",
    emoji: "⬟",
    desc: "Cybersecurity and cloud infrastructure.",
    logo: "🔐",
  },
];

export const TIER_COLOR: Record<string, string> = {
  title: "#ffd700",
  platinum: "#00f5ff",
  gold: "#ffb7c5",
  associate: "rgba(255,255,255,0.35)",
};

export const HIGHLIGHTS = [
  {
    id: "ashking",
    name: "Ash King",
    type: "singer",
    title: "Bollywood Playback Sensation",
    description: 'Known for hits like "Laal Rang" and "Hawa Banke"',
    image: "/images/highlights/ashking.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/watch?v=example1",
    spotify: "https://spotify.com/artist/example1",
  },
  {
    id: "djnyk",
    name: "DJ NYK",
    type: "dj",
    title: "Asia's #1 Bollywood DJ",
    description: "Electronic dance music producer and festival headliner",
    image: "/images/highlights/djnyk.jpg",
    year: "2022",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example2",
    spotify: "https://spotify.com/artist/example2",
  },
  {
    id: "carryminati",
    name: "CarryMinati",
    type: "youtube",
    title: "India's Biggest YouTuber",
    description: "Gaming and comedy content creator with 40M+ subscribers",
    image: "/images/highlights/carryminati.jpg",
    year: "2023",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/@CarryMinati",
    spotify: null,
  },
  {
    id: "bhuvanbam",
    name: "Bhuvan Bam",
    type: "youtube",
    title: "Comedy Creator Extraordinaire",
    description: "BB Ki Vines fame, multi-talented entertainer",
    image: "/images/highlights/bhuvanbam.jpg",
    year: "2022",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@BBKiVines",
    spotify: null,
  },
  {
    id: "divyakumar",
    name: "Divya Kumar",
    type: "singer",
    title: "Versatile Vocalist",
    description: 'Known for "Gali Gali" and "Jhoom Barabar Jhoom"',
    image: "/images/highlights/divyakumar.jpg",
    year: "2021",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example3",
    spotify: "https://spotify.com/artist/example3",
  },
  {
    id: "djchetas",
    name: "DJ Chetas",
    type: "dj",
    title: "Bollywood Remix King",
    description: "Mumbai-based DJ with international tours",
    image: "/images/highlights/djchetas.jpg",
    year: "2021",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example4",
    spotify: "https://spotify.com/artist/example4",
  },
  {
    id: "mumbikernikhil",
    name: "Mumbiker Nikhil",
    type: "youtube",
    title: "Travel Vlogger",
    description: "Motorcycle travel and lifestyle content creator",
    image: "/images/highlights/mumbikernikhil.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@MumbikerNikhil",
    spotify: null,
  },
  {
    id: "akruti",
    name: "Akruti",
    type: "singer",
    title: "Indie Pop Artist",
    description: "Known for unique blend of Indian and Western music",
    image: "/images/highlights/akruti.jpg",
    year: "2022",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example5",
    spotify: "https://spotify.com/artist/example5",
  },
  {
    id: "djrukh",
    name: "DJ RUKH",
    type: "dj",
    title: "EDM Specialist",
    description: "Electronic music producer and festival DJ",
    image: "/images/highlights/djrukh.jpg",
    year: "2023",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example6",
    spotify: "https://spotify.com/artist/example6",
  },
];
