// app/utils/data.ts
import { EventItem, MerchItem, SponsorItem } from "@/types";

export const EVENTS: EventItem[] = [
  {
    id: "art-club-competition",
    icon: "🎨",
    name: "Art Club Competition",
    tagline: "Creative Expression",
    description:
      "Participants showcase their artistic talents in various mediums and compete for recognition.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ff69b4",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "09:00 AM - 10:30 AM",
    tags: ["Art", "Competition", "Creative"],
    rules: [
      "Participants must bring their own art materials.",
      "Only original works are allowed.",
      "Time limit will be strictly enforced.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Open to all students with artistic interests.",
      "Format: Create and submit artwork on the spot.",
      "Duration: As per event schedule.",
      "Evaluation: Creativity, technique, and presentation.",
    ],
  },
  {
    id: "photography-competition",
    icon: "📷",
    name: "Photography Club Competition - Photos",
    tagline: "Capture the Moment",
    description:
      "Photographers compete to capture the best moments following given themes and criteria.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#06b6d4",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "10:30 AM - 1:00 PM",
    tags: ["Photography", "Competition", "Visual"],
    rules: [
      "Participants must bring their own cameras or equipment.",
      "Only original photos taken during the competition are allowed.",
      "Post-processing is not permitted on-site.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Open to all photography enthusiasts.",
      "Format: Capture and submit photos based on given themes.",
      "Duration: As per event schedule.",
      "Evaluation: Composition, creativity, technical skill.",
    ],
  },
  {
    id: "mehandi-competition",
    icon: "🤚",
    name: "Mehandi Competition",
    tagline: "Traditional Art",
    description:
      "Participants create intricate mehandi designs and compete for artistic excellence.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ff6b6b",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "02:00 PM - 03:30 PM",
    tags: ["Mehandi", "Traditional", "Art"],
    rules: [
      "Only natural mehandi is allowed.",
      "Participants must bring their own mehandi materials.",
      "Time limit will be strictly enforced.",
      "No external help or reference materials permitted.",
    ],
    guidelines: [
      "Open to all students interested in traditional art.",
      "Format: Create mehandi designs on hands or other surfaces.",
      "Duration: As per event schedule.",
      "Evaluation: Design complexity, neatness, creativity.",
    ],
  },
  {
    id: "fashion-show",
    icon: "👗",
    name: "Fashion Show",
    tagline: "Style on Stage",
    description:
      "Designers showcase their creations through live runway presentations and compete for style awards.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ec4899",
    day: 3,
    teamSize: "Individual and team participation",
    resultAnnouncement: null,
    dayTimeVenue: "03:30 PM - 05:00 PM",
    tags: ["Fashion", "Design", "Runway"],
    rules: [
      "Participants must bring their own outfits and accessories.",
      "Only original designs are allowed.",
      "Time limit for presentations will be enforced.",
      "Music and props must be approved beforehand.",
    ],
    guidelines: [
      "Open to all fashion designers and models.",
      "Format: Runway presentation with designed outfits.",
      "Duration: As per event schedule.",
      "Evaluation: Design originality, presentation, and overall impact.",
    ],
  },
  {
    id: "singing-competition",
    icon: "🎤",
    name: "Singing Competition",
    tagline: "Voice of the Soul",
    description:
      "Vocalists perform and compete based on vocal skill, song choice, and stage presence.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#8b5cf6",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "05:00 PM - 06:30 PM",
    tags: ["Singing", "Music", "Vocal"],
    rules: [
      "Participants must bring their own backing tracks (if allowed).",
      "Only appropriate songs and lyrics are permitted.",
      "Time limit for performances will be strictly enforced.",
      "No lip-syncing is allowed unless specified.",
    ],
    guidelines: [
      "Open to all vocal performers.",
      "Format: Live performance with chosen song.",
      "Duration: As per event schedule.",
      "Evaluation: Vocal technique, song choice, and stage performance.",
    ],
  },
  {
    id: "dance-competition",
    icon: "💃",
    name: "Dance Competition",
    tagline: "Rhythm in Motion",
    description:
      "Dancers and groups showcase their choreography and compete for dance supremacy.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#f97316",
    day: 3,
    teamSize: "Individual and group participation",
    resultAnnouncement: null,
    dayTimeVenue: "06:30 PM - 08:00 PM",
    tags: ["Dance", "Choreography", "Performance"],
    rules: [
      "Participants must bring their own costumes and music.",
      "Only original choreography is allowed.",
      "Time limit for performances will be strictly enforced.",
      "Safety guidelines must be followed during performances.",
    ],
    guidelines: [
      "Open to all dancers and dance groups.",
      "Format: Stage performance with choreographed routine.",
      "Duration: As per event schedule.",
      "Evaluation: Technique, creativity, synchronization, and overall performance.",
    ],
  },
  {
    id: "prize-distribution",
    icon: "🏆",
    name: "Prize Distribution",
    tagline: "Celebrating Excellence",
    description:
      "Official ceremony to recognize and award winners across all competition categories.",
    date: "Day 3",
    venue: "TBA",
    prize: "Awards",
    fee: "Free",
    color: "#ffd700",
    day: 3,
    teamSize: "All participants",
    resultAnnouncement: "Final Results",
    dayTimeVenue: "08:00 PM - 09:30 PM",
    tags: ["Awards", "Ceremony", "Closing"],
    rules: [
      "Attendance is mandatory for all winners.",
      "Participants must bring valid ID for prize collection.",
      "Organizers' decisions on prize distribution are final.",
    ],
    guidelines: [
      "Open to all festival participants and attendees.",
      "Format: Award ceremony for competition winners.",
      "Duration: As per event schedule.",
      "Evaluation: Recognition of achievements and contributions.",
    ],
  },
  {
    id: "dj-night",
    icon: "🎧",
    name: "DJ Night",
    tagline: "Beats till Dawn",
    description:
      "DJs showcase their mixing skills and keep the energy high with the latest tracks.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#a78bfa",
    day: 3,
    teamSize: "DJ performance",
    resultAnnouncement: null,
    dayTimeVenue: "09:30 PM - 10:00 PM",
    tags: ["Music", "DJ", "Party"],
    rules: [
      "DJs must bring their own equipment and music collection.",
      "Only appropriate music is allowed for the venue.",
      "Time slots will be strictly enforced.",
      "Sound levels must be maintained at reasonable levels.",
    ],
    guidelines: [
      "Open to all DJs and music enthusiasts.",
      "Format: Live DJ performance with music mixing.",
      "Duration: As per event schedule.",
      "Evaluation: Track selection, mixing skills, crowd engagement.",
    ],
  },
  ];

export const ROADMAP = [
  {
    day: 1,
    date: "April 9",
    title: "Opening Day",
    subtitle: "Culture Awakens",
    color: "#ff88aa",
    schedule: [
      { time: "8:00 AM", event: "Registration & Inauguration" },
      { time: "9:00 AM", event: "Inaugural Function" },
      { time: "10:00 AM", event: "Solo Classical" },
      { time: "11:00 AM", event: "Solo Western" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Group Classical" },
      { time: "2:00 PM", event: "Group Western" },
      { time: "3:00 PM", event: "Dance Finals" },
      { time: "4:00 PM", event: "Prize Distribution" },
      { time: "5:00 PM", event: "Band Performance" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 1" },
    ],
  },
  {
    day: 2,
    date: "April 10",
    title: "Battle Day",
    subtitle: "Legends Clash",
    color: "#9b59f5",
    schedule: [
      { time: "8:00 AM", event: "Registration" },
      { time: "9:00 AM", event: "Drama Competition" },
      { time: "10:00 AM", event: "Skit Competition" },
      { time: "11:00 AM", event: "Mono Act" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Gaming Competition" },
      { time: "2:00 PM", event: "Technical Events" },
      { time: "3:00 PM", event: "Singing Competition" },
      { time: "4:00 PM", event: "Instrumental Performance" },
      { time: "5:00 PM", event: "Battle of Bands" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 2" },
    ],
  },
  {
    day: 3,
    date: "April 11",
    title: "Star Night",
    subtitle: "Champions Rise",
    color: "#ffd700",
    schedule: [
      { time: "8:00 AM", event: "Registration" },
      { time: "9:00 AM", event: "Art Competition" },
      { time: "10:00 AM", event: "Photography Competition" },
      { time: "11:00 AM", event: "Mehandi Competition" },
      { time: "12:00 PM", event: "Lunch Break" },
      { time: "1:00 PM", event: "Fashion Show" },
      { time: "2:00 PM", event: "Singing Finals" },
      { time: "3:00 PM", event: "Dance Finals" },
      { time: "4:00 PM", event: "Prize Distribution" },
      { time: "5:00 PM", event: "Band Performance" },
      { time: "6:00 PM", event: "DJ Night" },
      { time: "7:00 PM", event: "Cultural Night" },
      { time: "8:00 PM", event: "Comedy Show" },
      { time: "9:00 PM", event: "Magic Show" },
      { time: "10:00 PM", event: "End of Day 3" },
    ],
  },
];

export const MERCH: MerchItem[] = [
  {
    id: "black-tshirt",
    name: "Black Festival Tee",
    description:
      "Premium black cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/Black_Dragon.jpg__1_-removebg-preview.png",
    color: "#000000",
    tag: "Classic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ffffff",
    glowColor: "#ffd700",
  },
  {
    id: "white-tshirt",
    name: "White Festival Tee",
    description:
      "Premium white cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/White_Fish.jpg-removebg-preview.png",
    color: "#ffffff",
    tag: "Fresh",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ff0000",
  },
  {
    id: "sakura-tshirt",
    name: "Sakura Festival Tee",
    description:
      "Premium cotton tee with ATULYAM sakura design featuring Japanese cherry blossom elements and festival logo.",
    price: 350,
    icon: "/images/merch/Beige_Sakura.jpg-removebg-preview.png",
    color: "#be185d",
    tag: "Spring Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
  {
    id: "galaxy-tshirt",
    name: "Galaxy Festival Tee",
    description:
      "Premium cotton tee with ATULYAM galaxy design featuring stars and cosmic elements on the back.",
    price: 350,
    icon: "/Beige_Dragon.jpg-removebg-preview.png",
    color: "#4a5568",
    tag: "Limited Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
];

export const SPONSORS: SponsorItem[] = [
  {
    name: "jio saavn",
    tier: "platinum",
    emoji: "🎵",
    desc: "Official Music Streaming Partner",
    logo: "/sponers-logo/JioSaavn.png",
  },
  {
    name: "Nodwin gaming",
    tier: "platinum",
    emoji: "🎮",
    desc: "Gaming Partner",
    logo: "/sponers-logo/nodwingaming.png",
  },
  {
    name: "Krafton",
    tier: "platinum",
    emoji: "🏁",
    desc: "Gaming Partner",
    logo: "/sponers-logo/KRAFTON.png",
  },
  {
    name: "College campus tour",
    tier: "associate",
    emoji: "🧭",
    desc: "Gaming Partner",
    logo: "/sponers-logo/campustour.png",
  },
  {
    name: "Ease my trip",
    tier: "gold",
    emoji: "✈️",
    desc: "Travel Partner",
    logo: "/sponers-logo/easemyTrip.png",
  },
  {
    name: "Geeks for Geeks",
    tier: "title",
    emoji: "💻",
    desc: "Official Platform Partner",
    logo: "/sponers-logo/gfg.png",
  },
  {
    name: "Unstop",
    tier: "platinum",
    emoji: "🚀",
    desc: "Hackathon Partner",
    logo: "/sponers-logo/Unstop.png",
  },
  {
    name: "Coca Cola",
    tier: "gold",
    emoji: "🥤",
    desc: "Beverage Partner",
    logo: "/sponers-logo/cocacola.png",
  },
  {
    name: "Urban Water Filter",
    tier: "gold",
    emoji: "💧",
    desc: "Water Filter Event Sponsor",
    logo: "/sponers-logo/urbanwater.jpg",
  },
  {
    name: "todo hotel",
    tier: "associate",
    emoji: "🏨",
    desc: "Hospitality Partner",
    logo: "/sponers-logo/todohotel.png",
  },
  {
    name: "echo of arunachal",
    tier: "associate",
    emoji: "📰",
    desc: "Media Partner",
    logo: "/sponers-logo/echo.jpeg",
  },
  {
    name: "Dopamine",
    tier: "associate",
    emoji: "👕",
    desc: "Merchandise Partner",
    logo: "/sponers-logo/dopamine.png",
  },
  {
    name: "NE Departmental",
    tier: "associate",
    emoji: "🤝",
    desc: "Partner",
    logo: "/sponers-logo/ne.png",
  },
  {
    name: "Renu Beverages",
    tier: "associate",
    emoji: "🥤",
    desc: "Partner",
    logo: "/sponers-logo/renu.jpeg",
  },
];

export const TIER_COLOR: Record<string, string> = {
  title: "#ffd700",
  platinum: "#00f5ff",
  gold: "#ffb7c5",
  associate: "rgba(255,255,255,0.35)",
};

export const HIGHLIGHTS = [
  {
    id: "ashking",
    name: "Ash King",
    type: "singer",
    title: "Bollywood Playback Sensation",
    description: 'Known for hits like "Laal Rang" and "Hawa Banke"',
    image: "/images/highlights/ashking.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/watch?v=example1",
    spotify: "https://spotify.com/artist/example1",
  },
  {
    id: "djnyk",
    name: "DJ NYK",
    type: "dj",
    title: "Asia's #1 Bollywood DJ",
    description: "Electronic dance music producer and festival headliner",
    image: "/images/highlights/djnyk.jpg",
    year: "2022",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example2",
    spotify: "https://spotify.com/artist/example2",
  },
  {
    id: "carryminati",
    name: "CarryMinati",
    type: "youtube",
    title: "India's Biggest YouTuber",
    description: "Gaming and comedy content creator with 40M+ subscribers",
    image: "/images/highlights/carryminati.jpg",
    year: "2023",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/@CarryMinati",
    spotify: null,
  },
  {
    id: "bhuvanbam",
    name: "Bhuvan Bam",
    type: "youtube",
    title: "Comedy Creator Extraordinaire",
    description: "BB Ki Vines fame, multi-talented entertainer",
    image: "/images/highlights/bhuvanbam.jpg",
    year: "2022",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@BBKiVines",
    spotify: null,
  },
  {
    id: "divyakumar",
    name: "Divya Kumar",
    type: "singer",
    title: "Versatile Vocalist",
    description: 'Known for "Gali Gali" and "Jhoom Barabar Jhoom"',
    image: "/images/highlights/divyakumar.jpg",
    year: "2021",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example3",
    spotify: "https://spotify.com/artist/example3",
  },
  {
    id: "djchetas",
    name: "DJ Chetas",
    type: "dj",
    title: "Bollywood Remix King",
    description: "Mumbai-based DJ with international tours",
    image: "/images/highlights/djchetas.jpg",
    year: "2021",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example4",
    spotify: "https://spotify.com/artist/example4",
  },
  {
    id: "mumbikernikhil",
    name: "Mumbiker Nikhil",
    type: "youtube",
    title: "Travel Vlogger",
    description: "Motorcycle travel and lifestyle content creator",
    image: "/images/highlights/mumbikernikhil.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@MumbikerNikhil",
    spotify: null,
  },
  {
    id: "akruti",
    name: "Akruti",
    type: "singer",
    title: "Indie Pop Artist",
    description: "Known for unique blend of Indian and Western music",
    image: "/images/highlights/akruti.jpg",
    year: "2022",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example5",
    spotify: "https://spotify.com/artist/example5",
  },
  {
    id: "djrukh",
    name: "DJ RUKH",
    type: "dj",
    title: "EDM Specialist",
    description: "Electronic music producer and festival DJ",
    image: "/images/highlights/djrukh.jpg",
    year: "2023",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example6",
    spotify: "https://spotify.com/artist/example6",
  },
];
