// app/utils/data.ts
import { EventItem, MerchItem, SponsorItem } from "@/types";

export const EVENTS: EventItem[] = [
  {
    id: "ideathon",
    icon: "💡",
    name: "IdeaThon",
    tagline: "Design for Sustainable Impact",
    description:
      "Teams identify a real area-based challenge or build a new value-driven concept with sustainability at the center.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#ff88aa",
    day: 1,
    teamSize: "2-4 participants",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Innovation", "Sustainability", "Presentation"],
    rules: [
      "Use of AI tools/design software is permitted, but originality must be maintained.",
      "Plagiarism or copying of existing projects will lead to disqualification.",
      "Time slots for presentation will be strictly followed.",
      "The decision of the judges will be final and binding.",
    ],
    guidelines: [
      "Team Formation: Each team can consist of 2-4 participants. Participants can be from the same or different departments. Cross-disciplinary collaboration is encouraged.",
      "Problem Statement: A large area layout will be provided by the organizers. Teams must select a specific portion of the area and either solve an existing problem or create something new.",
      "Focus on Sustainability: Solutions must align with sustainable development goals and prioritize eco-friendly, resource-efficient, long-term viable methods.",
      "Deliverables: Submit a sketch/diagram/layout and a 5-7 minute presentation before the deadline.",
      "Evaluation Criteria: Innovation & Creativity, Relevance, Sustainability, Feasibility, Presentation, Cross Questioning.",
      "General Instructions: Bring stationery and laptop (if required); follow timeline and coordinate with organizers for queries.",
    ],
  },
  {
    id: "verilog-coding",
    icon: "🧠",
    name: "VERILOG CODING",
    tagline: "Digital Logic by Code",
    description:
      "Participants design and implement digital circuits using Verilog HDL under time constraints.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#00f5ff",
    day: 1,
    teamSize: "individual only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Verilog", "EDA Playground", "Individual"],
    rules: [
      "Participants must bring their own laptops with access to EDA Playground.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; participation is individual only.",
      "Format: Design and implement digital circuits using Verilog HDL.",
      "Duration: As per event schedule.",
      "Evaluation: Based on correctness, efficiency, and optimization.",
    ],
  },
  {
    id: "line-follower-robot",
    icon: "🤖",
    name: "LINE FOLLOWER ROBOT",
    tagline: "Speed with Precision",
    description:
      "Autonomous robots must accurately follow a predefined black-line track on a white surface.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#ffd700",
    day: 1,
    teamSize: "groups of max 3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Autonomous", "IR Sensors", "Robotics"],
    rules: [
      "Only IR sensors or light sensors may be used for line detection.",
      "Robots must adhere to max dimensions (25cm x 25cm) and weight (2kg).",
      "External wireless/manual control is prohibited.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; participation in groups of max 3 members.",
      "Format: Robots must autonomously follow a track marked with black lines on white surface.",
      "Duration: As per event schedule.",
      "Evaluation: Accuracy, speed, and penalties for leaving track/manual intervention.",
    ],
  },
  {
    id: "water-filtration-race",
    icon: "💧",
    name: "Water Filtration Race",
    tagline: "Clarity Under Pressure",
    description:
      "Teams build a filter on the spot using organizer kits and compete on clarity, speed, and design.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "15k for prize pool",
    fee: "TBA",
    color: "#4ade80",
    day: 1,
    teamSize: "2-3 members per team",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Filtration", "Lab Test", "Design Build"],
    rules: [
      "No external material is allowed; only organizer-provided kit can be used.",
      "Inter college team members are not allowed.",
      "Inter specialization are allowed.",
      "Time limit: Max 90 minutes (30 min design + 60 min filtering).",
      "Filter must be stable and fill filtered water at given specific container height.",
      "Disqualification for unapproved materials, spillage, or failure within time.",
    ],
    guidelines: [
      "Eligibility: For all B.E., B.Tech, and other college students.",
      "All teams receive equal testing water quantity; testing done in laboratory with digital turbidity meter.",
      "Scoring (100 points): Clarity 50, Filtration speed 30, Design and innovation 20.",
    ],
  },
  {
    id: "minimalist-circuit-challenge",
    icon: "🧩",
    name: "Minimalist Circuit Challenge",
    tagline: "Do More with Less",
    description:
      "Teams design and build optimized circuits using minimum components with strong reliability and clarity.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "Winner Team: ₹7,000 - Runner-Up Team: 5,000",
    fee: "TBA",
    color: "#60a5fa",
    day: 1,
    teamSize: "A team must consist of 2-3 members",
    resultAnnouncement: null,
    dayTimeVenue: "To be Announced",
    tags: ["Circuit Build", "Optimization", "State Only"],
    rules: [
      "Team size: 2-3 members.",
      "Time limit: 2.5 hours for circuit building.",
      "Only provided components are allowed.",
      "All circuits must be built on-site; pre-built modules are not allowed.",
      "Safety guidelines must be followed.",
      "Judges' decision is final.",
      "Teams from outside the state are not eligible.",
      "Inter-college and inter-branch teams are permitted within the state.",
      "Any violation leads to disqualification.",
    ],
    guidelines: [
      "Open only to students currently enrolled in state engineering, diploma, or science programs.",
      "Inter-college and inter-specialization teams are allowed within the state.",
      "Round 1: Problem statement selection.",
      "Round 2: Design and implementation (2.5 hours).",
      "Round 3: Presentation and evaluation.",
      "Judging: Innovation 25%, Implementation 25%, Efficiency 25%, Teamwork and explanation 25%.",
    ],
  },
  {
    id: "rocket-aviation-task",
    icon: "🚀",
    name: "ROCKET AVIATION TASK",
    tagline: "Model, Validate, Present",
    description:
      "Participants bring pre-made models and are evaluated for feasibility and solution clarity.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#f97316",
    day: 1,
    teamSize:
      "Group of max 3 member and individual participation is also allowed",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Aviation", "Model Based", "Engineering"],
    rules: [
      "Only provided tools/software may be used.",
      "External reference materials are not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students.",
      "Format: Participants bring their pre-made model at competition time.",
      "Duration: 60 minutes.",
      "Evaluation: Accuracy, feasibility, and clarity of solution.",
    ],
  },
  {
    id: "circuit-debugging",
    icon: "🔧",
    name: "CIRCUIT DEBUGGING",
    tagline: "Find Faults, Restore Function",
    description:
      "A multi-round debugging challenge with MCQs, circuit design, and real fault-finding under strict timing.",
    date: "Day 1",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#06b6d4",
    day: 1,
    teamSize: "Teams of 1-3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Debugging", "E&E", "Round Based"],
    rules: [
      "Teams must consist of 1-3 members from the same institute.",
      "Only Electrical and Electronics specialization students are eligible.",
      "Inter-NIT collaboration is strictly not allowed.",
      "Unauthorized reference material, internet, or devices are prohibited.",
      "Judges and coordinators decisions are final and binding.",
      "Participants must strictly follow round time limits.",
      "Misconduct or rule violations lead to immediate disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to NIT Arunachal Pradesh Electrical and Electronics branch specializations only.",
      "Team Formation: Teams of 1-3 members.",
      "Round 1: 20 debugging questions, 25 minutes.",
      "Round 2: Top 10 design optimized circuits from 2 problem statements, 20 minutes.",
      "Round 3: Top 5 debug and test one faulty circuit, 20 minutes.",
      "Evaluation: Error identification, creativity, efficiency, practical debugging, time management, and clarity.",
    ],
  },
  {
    id: "bridge-making",
    icon: "🌉",
    name: "Bridge making",
    tagline: "Strength Meets Aesthetics",
    description:
      "Teams build bridges using only provided sticks and glue, then face progressive center-load failure testing.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#a78bfa",
    day: 2,
    teamSize: "2-3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Structures", "Load Test", "Civil Build"],
    rules: [
      "Inter college team members are not allowed.",
      "Inter specialization are allowed.",
      "Any extra glue, tape, string, wire, nails, pins, or materials lead to disqualification.",
      "No external cables, wires, or reinforcements are allowed.",
      "Teams must bring completed bridge for inspection/testing on competition day.",
      "Non-compliant bridges may be rejected before testing.",
      "Only organizers/judges handle loading process.",
      "Disqualification for violating material and dimension/submission rules.",
    ],
    guidelines: [
      "Eligibility: B.E./B.Tech and other college students.",
      "Team size: 2-3 members.",
      "Materials: Organizer-provided ice-cream sticks and glue only.",
      "Design: Any bridge type (beam, truss, arch, etc.) using provided materials.",
      "Dimensions: Length min 55 cm, clear span 50 cm, deck width min 15 cm, no height restriction.",
      "Construction: Allowed before competition day but only with provided materials.",
      "Load Testing: Gradual center loading until failure.",
      "Evaluation: Strength 70%, aesthetics and neatness 30%.",
    ],
  },
  {
    id: "pcb-design",
    icon: "🟩",
    name: "PCB DESIGN",
    tagline: "From Schematic to 3D Board",
    description:
      "Teams design and simulate PCBs from given specs up to final 3D PCB output.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#22c55e",
    day: 2,
    teamSize: "teams of 1-2 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["PCB", "Simulation", "Layout"],
    rules: [
      "Only professional design software is allowed.",
      "Pre-prepared designs are strictly prohibited.",
      "Internet access during the round is not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; teams of 1-2 members.",
      "Format: Design and simulate PCB from given specification to final 3D design.",
      "Duration: As per event schedule.",
      "Evaluation: Correctness, layout optimization, industry practices, creativity, minimal track length.",
    ],
  },
  {
    id: "maze-follower-robot",
    icon: "🧭",
    name: "MAZE FOLLOWER ROBOT",
    tagline: "Autonomous Pathfinding",
    description:
      "Robots must autonomously navigate a maze from start to finish with high speed and accuracy.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#eab308",
    day: 2,
    teamSize: "groups of max 3 members",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Autonomous", "Maze", "Robotics"],
    rules: [
      "Robots must operate autonomously with no external/manual control.",
      "Modifications during the round are not allowed.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
      "Any malpractice will lead to disqualification.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; groups of max 3 members.",
      "Format: Robots navigate through maze autonomously from start to finish.",
      "Duration: As per event schedule.",
      "Evaluation: Speed and accuracy.",
    ],
  },
  {
    id: "mortal-kombat-showdown",
    icon: "🎮",
    name: "Mortal Kombat Showdown",
    tagline: "Controller Skill Arena",
    description:
      "Tournament format adapts to participation size with best-of match rounds and fair-play enforcement.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "₹15,000",
    fee: "TBA",
    color: "#ef4444",
    day: 2,
    teamSize: "Players register individually",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Esports", "Knockout", "1v1"],
    rules: [
      "Format is knockout or league-cum-knockout based on participant count.",
      "Matches on standard setups with provided controllers; personal controllers may be allowed.",
      "Each match best of 3 rounds; finals best of 5 rounds.",
    ],
    guidelines: [
      "Registration and briefing include rules, format, judging criteria, fair-play, and disqualification conditions.",
      "Participation through the official Google Form.",
    ],
  },
  {
    id: "component-identification",
    icon: "🔌",
    name: "Component Identification",
    tagline: "Know It, Use It, Build It",
    description:
      "A four-round identification and application challenge progressing from written tests to buzzer finals.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "1st: ₹6,000, 2nd: ₹4,000, 3rd: ₹2,000",
    fee: "TBA",
    color: "#14b8a6",
    day: 2,
    teamSize: "Individual participation only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Electronics", "Rounds", "Identification"],
    rules: [
      "Participants must report 15 minutes before event starts.",
      "Only qualified participants proceed to next round.",
      "External materials, gadgets, or mobile phones are prohibited.",
      "Judges' decisions are final and binding.",
      "Any misconduct leads to disqualification.",
    ],
    guidelines: [
      "Competition has 4 rounds; both inter-college and inter-specialization participation are allowed.",
      "Round 1: 30 questions (25 MCQ + 5 theoretical), 35 minutes; 15 qualify.",
      "Round 2: Identify components and state usage/applications, 20 minutes; 10 qualify.",
      "Round 3: Circuit completion and missing element identification, 30 minutes; 5 qualify.",
      "Round 4: Final buzzer round (WHO AM I?) for 30 minutes.",
    ],
  },
  {
    id: "assembly-disassembly",
    icon: "🛠️",
    name: "ASSEMBLY & DISASSEMBLY",
    tagline: "Accuracy Under Time",
    description:
      "Participants disassemble and reassemble mechanical systems correctly, focusing on speed and part identification.",
    date: "Day 2",
    venue: "To be Announced",
    prize: "TBA",
    fee: "TBA",
    color: "#64748b",
    day: 2,
    teamSize: "individual only",
    resultAnnouncement: null,
    dayTimeVenue: null,
    tags: ["Mechanical", "Hands On", "Individual"],
    rules: [
      "Safety gear (gloves, goggles) must be worn at all times.",
      "Mishandling or damaging components will result in disqualification.",
      "Only provided tools may be used.",
      "Mobile phones are not permitted during the competition.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Eligibility: Open to all UG/PG engineering students; individual participation only.",
      "Format: Disassemble and reassemble the given mechanical component/system within the time limit.",
      "Duration: 60 minutes.",
      "Evaluation: Accuracy, speed, and proper identification of parts.",
    ],
  },
  {
    id: "art-club-competition",
    icon: "🎨",
    name: "Art Club Competition",
    tagline: "Creative Expression",
    description:
      "Participants showcase their artistic talents in various mediums and compete for recognition.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ff69b4",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "09:00 AM - 10:30 AM",
    tags: ["Art", "Competition", "Creative"],
    rules: [
      "Participants must bring their own art materials.",
      "Only original works are allowed.",
      "Time limit will be strictly enforced.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Open to all students with artistic interests.",
      "Format: Create and submit artwork on the spot.",
      "Duration: As per event schedule.",
      "Evaluation: Creativity, technique, and presentation.",
    ],
  },
  {
    id: "photography-competition",
    icon: "📷",
    name: "Photography Club Competition - Photos", 
    tagline: "Capture the Moment",
    description:
      "Photographers compete to capture the best moments following given themes and criteria.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#06b6d4",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "10:30 AM - 1:00 PM",
    tags: ["Photography", "Competition", "Visual"],
    rules: [
      "Participants must bring their own cameras or equipment.",
      "Only original photos taken during the competition are allowed.",
      "Post-processing is not permitted on-site.",
      "Judges' decisions are final.",
    ],
    guidelines: [
      "Open to all photography enthusiasts.",
      "Format: Capture and submit photos based on given themes.",
      "Duration: As per event schedule.",
      "Evaluation: Composition, creativity, technical skill.",
    ],
  },
  {
    id: "mehandi-competition",
    icon: "🤚",
    name: "Mehandi Competition",
    tagline: "Traditional Art",
    description:
      "Participants create intricate mehandi designs and compete for artistic excellence.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ff6b6b",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "02:00 PM - 03:30 PM",
    tags: ["Mehandi", "Traditional", "Art"],
    rules: [
      "Only natural mehandi is allowed.",
      "Participants must bring their own mehandi materials.",
      "Time limit will be strictly enforced.",
      "No external help or reference materials permitted.",
    ],
    guidelines: [
      "Open to all students interested in traditional art.",
      "Format: Create mehandi designs on hands or other surfaces.",
      "Duration: As per event schedule.",
      "Evaluation: Design complexity, neatness, creativity.",
    ],
  },
  {
    id: "fashion-show",
    icon: "👗",
    name: "Fashion Show",
    tagline: "Style on Stage",
    description:
      "Designers showcase their creations through live runway presentations and compete for style awards.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#ec4899",
    day: 3,
    teamSize: "Individual and team participation",
    resultAnnouncement: null,
    dayTimeVenue: "03:30 PM - 05:00 PM",
    tags: ["Fashion", "Design", "Runway"],
    rules: [
      "Participants must bring their own outfits and accessories.",
      "Only original designs are allowed.",
      "Time limit for presentations will be enforced.",
      "Music and props must be approved beforehand.",
    ],
    guidelines: [
      "Open to all fashion designers and models.",
      "Format: Runway presentation with designed outfits.",
      "Duration: As per event schedule.",
      "Evaluation: Design originality, presentation, and overall impact.",
    ],
  },
  {
    id: "singing-competition",
    icon: "🎤",
    name: "Singing Competition",
    tagline: "Voice of the Soul",
    description:
      "Vocalists perform and compete based on vocal skill, song choice, and stage presence.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#8b5cf6",
    day: 3,
    teamSize: "Individual participation",
    resultAnnouncement: null,
    dayTimeVenue: "05:00 PM - 06:30 PM",
    tags: ["Singing", "Music", "Vocal"],
    rules: [
      "Participants must bring their own backing tracks (if allowed).",
      "Only appropriate songs and lyrics are permitted.",
      "Time limit for performances will be strictly enforced.",
      "No lip-syncing is allowed unless specified.",
    ],
    guidelines: [
      "Open to all vocal performers.",
      "Format: Live performance with chosen song.",
      "Duration: As per event schedule.",
      "Evaluation: Vocal technique, song choice, and stage performance.",
    ],
  },
  {
    id: "dance-competition",
    icon: "💃",
    name: "Dance Competition",
    tagline: "Rhythm in Motion",
    description:
      "Dancers and groups showcase their choreography and compete for dance supremacy.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#f97316",
    day: 3,
    teamSize: "Individual and group participation",
    resultAnnouncement: null,
    dayTimeVenue: "06:30 PM - 08:00 PM",
    tags: ["Dance", "Choreography", "Performance"],
    rules: [
      "Participants must bring their own costumes and music.",
      "Only original choreography is allowed.",
      "Time limit for performances will be strictly enforced.",
      "Safety guidelines must be followed during performances.",
    ],
    guidelines: [
      "Open to all dancers and dance groups.",
      "Format: Stage performance with choreographed routine.",
      "Duration: As per event schedule.",
      "Evaluation: Technique, creativity, synchronization, and overall performance.",
    ],
  },
  {
    id: "prize-distribution",
    icon: "🏆",
    name: "Prize Distribution",
    tagline: "Celebrating Excellence",
    description:
      "Official ceremony to recognize and award winners across all competition categories.",
    date: "Day 3",
    venue: "TBA",
    prize: "Awards",
    fee: "Free",
    color: "#ffd700",
    day: 3,
    teamSize: "All participants",
    resultAnnouncement: "Final Results",
    dayTimeVenue: "08:00 PM - 09:30 PM",
    tags: ["Awards", "Ceremony", "Closing"],
    rules: [
      "Attendance is mandatory for all winners.",
      "Participants must bring valid ID for prize collection.",
      "Organizers' decisions on prize distribution are final.",
    ],
    guidelines: [
      "Open to all festival participants and attendees.",
      "Format: Award ceremony for competition winners.",
      "Duration: As per event schedule.",
      "Evaluation: Recognition of achievements and contributions.",
    ],
  },
  {
    id: "dj-night",
    icon: "🎧",
    name: "DJ Night",
    tagline: "Beats till Dawn",
    description:
      "DJs showcase their mixing skills and keep the energy high with the latest tracks.",
    date: "Day 3",
    venue: "TBA",
    prize: "TBA",
    fee: "TBA",
    color: "#a78bfa",
    day: 3,
    teamSize: "DJ performance",
    resultAnnouncement: null,
    dayTimeVenue: "09:30 PM - 10:00 PM",
    tags: ["Music", "DJ", "Party"],
    rules: [
      "DJs must bring their own equipment and music collection.",
      "Only appropriate music is allowed for the venue.",
      "Time slots will be strictly enforced.",
      "Sound levels must be maintained at reasonable levels.",
    ],
    guidelines: [
      "Open to all DJs and music enthusiasts.",
      "Format: Live DJ performance with music mixing.",
      "Duration: As per event schedule.",
      "Evaluation: Track selection, mixing skills, crowd engagement.",
    ],
  },
];

export const ROADMAP = [
  {
    day: 1,
    date: "April 9",
    title: "Opening Day",
    subtitle: "Culture Awakens",
    color: "#ff88aa",
    schedule: [
      { time: "09:00 AM - 10:30 AM", event: "Writing Club - Anime is Life", venue: "TBA" },
      { time: "10:30 AM - 1:00 PM", event: "Humour Club Competition", venue: "TBA" },
      { time: "01:00 PM - 02:00 PM", event: "Lunch Break", venue: "TBA" },
      { time: "02:00 PM - 03:30 PM", event: "Poetry Club - Anime is Life", venue: "TBA" },
      { time: "03:30 PM - 05:00 PM", event: "Drama Club Performance", venue: "TBA" },
      { time: "02:00 PM - 3:00 PM", event: "Writing Club - Anime is Life", venue: "TBA" },
      { time: "3:00 PM - 04:30 PM", event: "Voice OF Atulyam Round-1", venue: "TBA" },
      { time: "04:30 PM - 06:00 PM", event: "Pottery Club Competition", venue: "TBA" },
      { time: "06:00 PM - 07:00 PM", event: "SOLO&DUO DANCE ROUND-1", venue: "TBA" },
      { time: "07:00 PM - 08:30 PM", event: "Battle of Bands-ROUND-1", venue: "TBA" },
      { time: "08:30 PM - 10:00 PM", event: "Artist Night", venue: "TBA" },
    ],
  },
  {
    day: 2,
    date: "April 10",
    title: "Battle Day",
    subtitle: "Legends Clash",
    color: "#9b59f5",
    schedule: [
      { time: "09:00 AM - 10:30 AM", event: "Writing Club - Anime is Life", venue: "TBA" },
      { time: "10:30 AM - 1:00 PM", event: "Humour Club Competition", venue: "TBA" },
      { time: "01:00 PM - 02:00 PM", event: "Lunch Break", venue: "TBA" },
      { time: "02:00 PM - 03:30 PM", event: "Poetry Club - Anime is Life", venue: "TBA" },
      { time: "03:30 PM - 05:00 PM", event: "Drama Club Performance", venue: "TBA" },
      { time: "02:00 PM - 3:00 PM", event: "Writing Club - Anime is Life", venue: "TBA" },
      { time: "3:00 PM - 4:30 PM", event: "Voice OF Atulyam Round-1", venue: "TBA" },
      { time: "4:40 PM - 6:40 PM", event: "Cosplay Competition", venue: "TBA" },
      { time: "6:50 PM - 7:40 PM", event: "Battle of Bands FINALE", venue: "TBA" },
      { time: "7:40 PM - 08:00 PM", event: "Sound Check", venue: "TBA" },
      { time: "08:00 PM - 09:30 PM", event: "Local Artist Night", venue: "TBA" },
    ],
  },
  {
    day: 3,
    date: "April 11",
    title: "Star Night",
    subtitle: "Champions Rise",
    color: "#ffd700",
    schedule: [
      { time: "09:00 AM - 10:30 AM", event: "Art Club Competition", venue: "TBA" },
      { time: "10:30 AM - 1:00 PM", event: "Photography Club Competition - Photos", venue: "TBA" },
      { time: "01:00 PM - 02:00 PM", event: "Lunch Break", venue: "TBA" },
      { time: "02:00 PM - 03:30 PM", event: "Mehandi Competition", venue: "TBA" },
      { time: "03:30 PM - 05:00 PM", event: "Fashion Show", venue: "TBA" },
      { time: "05:00 PM - 06:30 PM", event: "Singing Competition", venue: "TBA" },
      { time: "06:30 PM - 08:00 PM", event: "Dance Competition", venue: "TBA" },
      { time: "08:00 PM - 09:30 PM", event: "Prize Distribution", venue: "TBA" },
      { time: "09:30 PM - 10:00 PM", event: "DJ Night", venue: "TBA" },
    ],
  },
];

export const MERCH: MerchItem[] = [
  {
    id: "black-tshirt",
    name: "Black Festival Tee",
    description:
      "Premium black cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/Black_Dragon.jpg__1_-removebg-preview.png",
    color: "#000000",
    tag: "Classic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ffffff",
    glowColor: "#ffd700",
  },
  {
    id: "white-tshirt",
    name: "White Festival Tee",
    description:
      "Premium white cotton tee with the ATULYAM galaxy print on the back and star emblem on the chest.",
    price: 350,
    icon: "/images/merch/White_Fish.jpg-removebg-preview.png",
    color: "#ffffff",
    tag: "Fresh",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
    priceColor: "#ff0000",
  },
  {
    id: "sakura-tshirt",
    name: "Sakura Festival Tee",
    description:
      "Premium cotton tee with ATULYAM sakura design featuring Japanese cherry blossom elements and festival logo.",
    price: 350,
    icon: "/images/merch/Beige_Sakura.jpg-removebg-preview.png",
    color: "#be185d",
    tag: "Spring Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
  {
    id: "galaxy-tshirt",
    name: "Galaxy Festival Tee",
    description:
      "Premium cotton tee with ATULYAM galaxy design featuring stars and cosmic elements on the back.",
    price: 350,
    icon: "/Beige_Dragon.jpg-removebg-preview.png",
    color: "#4a5568",
    tag: "Limited Edition",
    sizes: ["S", "M", "L", "XL", "XXL"],
    registrationLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfc6bbr5Ks9ydlz9DWAK0eHJo3Z0UtgQZU5MpJsAiGzJEhHQ/viewform?usp=header",
  },
];

export const SPONSORS: SponsorItem[] = [
  {
    name: "jio saavn",
    tier: "platinum",
    emoji: "🎵",
    desc: "Official Music Streaming Partner",
    logo: "/sponers-logo/JioSaavn.png",
  },
  {
    name: "Nodwin gaming",
    tier: "platinum",
    emoji: "🎮",
    desc: "Gaming Partner",
    logo: "/sponers-logo/nodwingaming.png",
  },
  {
    name: "Krafton",
    tier: "platinum",
    emoji: "🏁",
    desc: "Gaming Partner",
    logo: "/sponers-logo/KRAFTON.png",
  },
  {
    name: "College campus tour",
    tier: "associate",
    emoji: "🧭",
    desc: "Gaming Partner",
    logo: "/sponers-logo/campustour.png",
  },
  {
    name: "Ease my trip",
    tier: "gold",
    emoji: "✈️",
    desc: "Travel Partner",
    logo: "/sponers-logo/easemyTrip.png",
  },
  {
    name: "Geeks for Geeks",
    tier: "title",
    emoji: "💻",
    desc: "Official Platform Partner",
    logo: "/sponers-logo/gfg.png",
  },
  {
    name: "Unstop",
    tier: "platinum",
    emoji: "🚀",
    desc: "Hackathon Partner",
    logo: "/sponers-logo/Unstop.png",
  },
  {
    name: "Coca Cola",
    tier: "gold",
    emoji: "🥤",
    desc: "Beverage Partner",
    logo: "/sponers-logo/cocacola.png",
  },
  {
    name: "Urban Water Filter",
    tier: "gold",
    emoji: "💧",
    desc: "Water Filter Event Sponsor",
    logo: "/sponers-logo/urbanwater.jpg",
  },
  {
    name: "todo hotel",
    tier: "associate",
    emoji: "🏨",
    desc: "Hospitality Partner",
    logo: "/sponers-logo/todohotel.png",
  },
  {
    name: "echo of arunachal",
    tier: "associate",
    emoji: "📰",
    desc: "Media Partner",
    logo: "/sponers-logo/echo.jpeg",
  },
  {
    name: "Dopamine",
    tier: "associate",
    emoji: "👕",
    desc: "Merchandise Partner",
    logo: "/sponers-logo/dopamine.png",
  },
  {
    name: "NE Departmental",
    tier: "associate",
    emoji: "🤝",
    desc: "Partner",
    logo: "/sponers-logo/ne.png",
  },
  {
    name: "Renu Beverages",
    tier: "associate",
    emoji: "🥤",
    desc: "Partner",
    logo: "/sponers-logo/renu.jpeg",
  },
];

export const TIER_COLOR: Record<string, string> = {
  title: "#ffd700",
  platinum: "#00f5ff",
  gold: "#ffb7c5",
  associate: "rgba(255,255,255,0.35)",
};

export const HIGHLIGHTS = [
  {
    id: "ashking",
    name: "Ash King",
    type: "singer",
    title: "Bollywood Playback Sensation",
    description: 'Known for hits like "Laal Rang" and "Hawa Banke"',
    image: "/images/highlights/ashking.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/watch?v=example1",
    spotify: "https://spotify.com/artist/example1",
  },
  {
    id: "djnyk",
    name: "DJ NYK",
    type: "dj",
    title: "Asia's #1 Bollywood DJ",
    description: "Electronic dance music producer and festival headliner",
    image: "/images/highlights/djnyk.jpg",
    year: "2022",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example2",
    spotify: "https://spotify.com/artist/example2",
  },
  {
    id: "carryminati",
    name: "CarryMinati",
    type: "youtube",
    title: "India's Biggest YouTuber",
    description: "Gaming and comedy content creator with 40M+ subscribers",
    image: "/images/highlights/carryminati.jpg",
    year: "2023",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/@CarryMinati",
    spotify: null,
  },
  {
    id: "bhuvanbam",
    name: "Bhuvan Bam",
    type: "youtube",
    title: "Comedy Creator Extraordinaire",
    description: "BB Ki Vines fame, multi-talented entertainer",
    image: "/images/highlights/bhuvanbam.jpg",
    year: "2022",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@BBKiVines",
    spotify: null,
  },
  {
    id: "divyakumar",
    name: "Divya Kumar",
    type: "singer",
    title: "Versatile Vocalist",
    description: 'Known for "Gali Gali" and "Jhoom Barabar Jhoom"',
    image: "/images/highlights/divyakumar.jpg",
    year: "2021",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example3",
    spotify: "https://spotify.com/artist/example3",
  },
  {
    id: "djchetas",
    name: "DJ Chetas",
    type: "dj",
    title: "Bollywood Remix King",
    description: "Mumbai-based DJ with international tours",
    image: "/images/highlights/djchetas.jpg",
    year: "2021",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example4",
    spotify: "https://spotify.com/artist/example4",
  },
  {
    id: "mumbikernikhil",
    name: "Mumbiker Nikhil",
    type: "youtube",
    title: "Travel Vlogger",
    description: "Motorcycle travel and lifestyle content creator",
    image: "/images/highlights/mumbikernikhil.jpg",
    year: "2023",
    day: "Day 2",
    date: "11 April",
    youtube: "https://youtube.com/@MumbikerNikhil",
    spotify: null,
  },
  {
    id: "akruti",
    name: "Akruti",
    type: "singer",
    title: "Indie Pop Artist",
    description: "Known for unique blend of Indian and Western music",
    image: "/images/highlights/akruti.jpg",
    year: "2022",
    day: "Day 1",
    date: "10 April",
    youtube: "https://youtube.com/watch?v=example5",
    spotify: "https://spotify.com/artist/example5",
  },
  {
    id: "djrukh",
    name: "DJ RUKH",
    type: "dj",
    title: "EDM Specialist",
    description: "Electronic music producer and festival DJ",
    image: "/images/highlights/djrukh.jpg",
    year: "2023",
    day: "Day 3",
    date: "12 April",
    youtube: "https://youtube.com/watch?v=example6",
    spotify: "https://spotify.com/artist/example6",
  },
];
